function C = solve_nl(degree, nodes)
% Solves for the unknown C using system of equations generated by Gauss
% quadrature rule
xmat = [];
for i = 0:degree
    xmat = [xmat; nodes.^i];
end

for i = 1:degree+1
    if mod(i-1, 2) == 0
        b(i) = 2/(i-1+1);
    else
        b(i) = 0;
    end
end

C = (xmat'*xmat)\(xmat'*b');


end